export const CREATE_POST = 'POSTS/CREATE_POST';
export const FETCH_POSTS = 'POSTS/FETCH_POSTS';
export const REQUEST_POSTS = 'POSTS/REQUEST_POSTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
